/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as TechniciansIndexRouteImport } from './routes/technicians/index'
import { Route as TechniciansIdRouteImport } from './routes/technicians/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansIndexRoute = TechniciansIndexRouteImport.update({
  id: '/technicians/',
  path: '/technicians/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansIdRoute = TechniciansIdRouteImport.update({
  id: '/technicians/$id',
  path: '/technicians/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/customers/$id': typeof CustomersIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/technicians/$id': typeof TechniciansIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/customers/$id': typeof CustomersIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/technicians/$id': typeof TechniciansIdRoute
  '/customers': typeof CustomersIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/technicians': typeof TechniciansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/customers/$id': typeof CustomersIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/technicians/$id': typeof TechniciansIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/inventory'
    | '/messages'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/stores'
    | '/customers/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/technicians/$id'
    | '/customers/'
    | '/jobs/'
    | '/technicians/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/inventory'
    | '/messages'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/stores'
    | '/customers/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/technicians/$id'
    | '/customers'
    | '/jobs'
    | '/technicians'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/inventory'
    | '/messages'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/stores'
    | '/customers/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/technicians/$id'
    | '/customers/'
    | '/jobs/'
    | '/technicians/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRoute
  CustomersIdRoute: typeof CustomersIdRoute
  JobsIdRoute: typeof JobsIdRoute
  JobsNewRoute: typeof JobsNewRoute
  TechniciansIdRoute: typeof TechniciansIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  TechniciansIndexRoute: typeof TechniciansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians/': {
      id: '/technicians/'
      path: '/technicians'
      fullPath: '/technicians/'
      preLoaderRoute: typeof TechniciansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians/$id': {
      id: '/technicians/$id'
      path: '/technicians/$id'
      fullPath: '/technicians/$id'
      preLoaderRoute: typeof TechniciansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRoute,
  CustomersIdRoute: CustomersIdRoute,
  JobsIdRoute: JobsIdRoute,
  JobsNewRoute: JobsNewRoute,
  TechniciansIdRoute: TechniciansIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  TechniciansIndexRoute: TechniciansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
